app/urls.py
from django.conf.urls import url

from app import views

urlpatterns=[
    url(r'^index/$',views.index,name='index'),

    url(r'^register/$',views.register,name='register'),

    url(r'^logout/$',views.logout,name='logout'),

    url(r'^login/$',views.login,name='login'),

    url(r'^account_check/$',views.account_check,name='account_check'),

    url(r'^detail/$',views.detail,name='detail'),

    url(r'^shop/(?P<id>\d+)/$',views.shop,name='shop'),

    url(r'^addcart/$',views.addcart,name='addcart'),

    url(r'^minuscart/$',views.minuscart,name='minuscart'),

    url(r'^add_cart/$',views.add_cart,name='add_cart'),

    url(r'^cart/$',views.cart,name='cart'),

    url(r'^deletecart/$',views.deletecart,name='deletecart'),

    url(r'^changestatus/$',views.changestatus,name='changestatus'),

    url(r'^generateorder/$',views.generateorder,name='generateorder'),

    url(r'^changeall/$',views.changeall,name='changeall'),

    url(r'^buy_immediatly/$',views.buy_immediatly,name='buy_immediatly'),

    url(r'^generateorder2/$',views.generateorder2,name='generateorder2'),
]

网易考拉/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls',namespace='app')),
]

app/models.py
from django.db import models

# Create your models here.
class Wheel(models.Model):
    name=models.CharField(max_length=100)
    img=models.CharField(max_length=100)

    class Meta:
        db_table='网易考拉——轮播图'

class Tuijian(models.Model):
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=100)

    class Meta:
        db_table = '网易考拉——推荐'

class User(models.Model):
    account=models.CharField(max_length=100,unique=True)
    password=models.CharField(max_length=300)
    phone=models.CharField(max_length=100)

    class Meta:
        db_table='网易考拉——注册表'

class Goods(models.Model):
    name=models.CharField(max_length=100)
    price=models.FloatField()
    img=models.CharField(max_length=100)
    store_num=models.IntegerField(default=20)

    class Meta:
        db_table='网易考拉——商品'

class Cart(models.Model):
    user=models.ForeignKey(User)

    goods=models.ForeignKey(Goods)

    number=models.IntegerField(default=0)

    isselect=models.BooleanField(default=True)

    isdelete=models.BooleanField(default=False)

    class Meta:
        db_table='网易考拉——购物车'

class Order(models.Model):
    user=models.ForeignKey(User)

    status=models.IntegerField(default=0)

    creat_time=models.DateTimeField(auto_now_add=True)

    update_time=models.DateTimeField(auto_now=True)

    identifier=models.CharField(max_length=300)

    class Meta:
        db_table='网易考拉——订单'

class OrderGoods(models.Model):
    order=models.ForeignKey(Order)

    goods=models.ForeignKey(Goods)

    number=models.IntegerField(default=0)

    class Meta:
        db_table='网易考拉——订单商品'

templates/cart.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>购物车-网易考拉海购</title>
    <meta content="telephone=no" name="format-detection"/>
    <meta content="email=no" name="format-detection"/>
    <meta name="keywords" content="跨境,海淘,进口,母婴用品,美妆个护,美食保健,美妆个护,海淘,商城"/>
    <meta name="description" content="网易考拉海购-安全、放心的跨境海淘网站，官方认证，正品保证。轻松购遍海外进口母婴，进口美食 ，进口美妆、进口电子数码，更多产品正陆续推出。"/>
    <meta name="renderer" content="webkit">
    <script src="https://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/cart2.js' %}" type="text/javascript" charset="utf-8"></script>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.1/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}"/>
    <style type="text/css">
        .bg {
            position: absolute;
            right: 38px;
            top: 40px;
            width: 290px;
            height: 20px;
            background: url(img/steps.png) no-repeat;
        }

        .mian {
            width: 1090px;
            padding: 0;
            margin-top: -24px;
            overflow: hidden;
            margin: 0 auto;
        }

        .cart_box {
            width: 100%;
        }

        .m_cart_box {
            margin-top: 40px;
        }

        .head {
            color: #999999;
            overflow: hidden;
        }

        .col1 {
            width: 114px;
            float: left;
            padding: 0 10px;
        }

        .u_chk {
            width: 17px;
            height: 18px;
            display: inline-block;
        }

        .col2 {
            width: 380px;
            float: left;
            padding: 0 10px;
        }

        .col3 {
            width: 132px;
            float: left;
            padding: 0 10px;
        }

        .col4 {
            width: 140px;
            float: left;
            padding: 0 10px;
        }

        .col5 {
            width: 100px;
            float: left;
            padding: 0 10px;
        }

        .col6 {
            width: 110px;
            float: left;
            padding: 0 7px;
            text-align: left;
        }

        .m_cart {
            margin-top: 15px;
            color: #333333;
        }

        .ware {
            padding: 10px 0 15px 10px;
            font-size: 18px;
            font-weight: bold;
            color: #333333;
        }

        .warename {
            margin-left: 3px;
            font-weight: bold;
            font-size: 18px;
        }

        .goods {
            border: 1px solid #EAEAEA;
        }

        .m_goods {
            list-style: none;
        }

        .goodsitm {
            border-bottom: 1px solid #EAEAEA;
            display: table;
            height: 120px;
        }

        .col10 {
            padding-right: 0;
            width: 37px;
            position: relative;
            display: table-cell;
            float: none;
            padding: 0 10px;
            vertical-align: middle;
        }

        .col12 {
            padding: 0 80px 0 0;
            width: 425px;
            float: none;
            display: table-cell;
            vertical-align: middle;
        }

        .imgwrap {
            float: left;
            width: 80px;
            height: 80px;
        }

        .imgwrap img {
            width: 80px;
            height: 80px;
        }

        .textwrap {
            margin-left: 20px;
            width: 310px;
            float: left;
        }

        .goodstit {
            height: 36px;
            line-height: 18px;
            overflow: hidden;
        }

        .goodstit a {
            color: #333333;
            font-size: 14px;
            display: block;
            line-height: 18px;
            font-weight: normal;
        }

        .col13 {
            width: 102px;
            font: none;
            display: table-cell;
            vertical-align: middle;
            padding: 0 10px;
        }

        .oldprice {
            color: #999999;
            display: block;
            width: 100px;
            text-align: left;
        }

        .newprice {
            font-weight: bold;
            font-size: 14px;
            color: #333333;
            display: block;
            width: 55px;
            text-align: left;
        }

        .u_acttag {
            display: inline-block;
            zoom: 1;
            padding: 0 8px;
            border: 1px solid #e31436;
            margin: 3px 0 0;
            height: 18px;
            line-height: 18px;
            text-align: center;
            font-size: 12px;
            color: #E31436;
            overflow: hidden;
            border-radius: 2px;
        }

        .col14 {
            width: 152px;
            float: none;
            display: table-cell;
            vertical-align: middle;
            padding: 0 10px;
        }

        .ctrnum_wrap {
            display: inline-block;
            border: 1px solid #CCCCCC;
            text-align: center;
            margin-top: 30px;
        }

        .add, .raduce {
            color: #ccc;
            background: #F3F3F3;
            cursor: default;
            border: 1px solid #ccc;
            display: inline-block;
            width: 22px;
            height: 22px;
            line-height: 22px;
            font-family: iconfont;
            text-decoration: none;
            text-align: center;
            float: left;
        }

        .ctrnum {
            width: 38px;
            padding: 4px 5px;
            margin: 0;
            line-height: 1;
            height: 14px;
            font-size: 14px;
            text-align: center;
            color: #333;
            border: none;
            box-sizing: content-box;
            float: left;
            border: #bcbcbc 1px solid;
            border-width: 1px 0;
        }

        .col15 {
            float: none;
            display: table-cell;
            vertical-align: middle;
            width: 100px;
            padding: 0 10px;
            text-align: center;
        }

        .sum {
            font-weight: bold;
            font-size: 14px;
        }

        .col16 {
            float: none;
            display: table-cell;
            vertical-align: middle;
            width: 110px;
            padding: 0 7px;
            text-align: left;
        }

        .u_opt {
            display: block;
            margin-top: 6px;
            color: #333333;
            cursor: pointer;
        }

        .cartinfo {
            padding: 10px 43px 10px 20px;
            text-align: right;
            white-space: nowrap;
            border: 1px solid #EAEAEA;
            overflow: hidden;
        }

        .taxnum, .allsum, .discunt {
            display: inline-block;
            zoom: 1;
            margin-right: 20px;
            font-size: 12px;
        }

        .totalbox {
            height: 62px;
            position: relative;
            margin-top: 35px;
            border: 1px solid #EAEAEA;
            background: #F8F8F8;
        }

        .gobuy {
            height: 62px;
            width: 120px;
            line-height: 62px;
            text-align: center;
            background: #e31436;
            color: #FFFFFF;
            font-size: 18px;
            cursor: pointer;
            position: absolute;
            right: 0;
            top: 0;
        }
    </style>
</head>
<body>
<div class="header">
    <div class="header-1">
        <div class="topnav">
            <div class="topnav-left-1">
                考拉欢迎您！
                {% if token %}
                    <span id="user-ifo">
                                <span>{{ user.account }}</span>
						</span>
                {% else %}
                    <span id="user-ifo">
                                <a href="login.html">登录</a>
                                <span>|</span>
							    <a href="register.html">免费注册</a>
						</span>
                {% endif %}
            </div>
            <div class="topnav-left-2">
                <div id="tel-img"></div>
                <a href="#" id="tel-word">手机考拉海购 </a>
            </div>
            <div id="tel-ewmimg">
                <img src="{% static 'picture/2dcode-app3.jpg' %}" height="116px" width="116px"/>
                <p><strong>下载app</strong></p>
                <p><strong>赢取1000元新人大礼包</strong></p>
            </div>

            <div class="topnav-right">
                <ul>
                    <li>
                        <a href="{% url 'app:index' %}"><span class="qiandao"></span>Home</a>
                        <span>|</span>
                    </li>
                    <li>
                        <a href="#">我的订单</a>
                        <span>|</span>
                    </li>
                    <li class="person-home-1">
                        <a href="#">个人中心</a>
                        <span>|</span>
                    </li>
                    <li class="person-home-2">
                        <a href="#">客户服务</a>
                        <span>|</span>
                    </li>
                    <li>
                        <a href="#">游戏充值</a>
                        <span>|</span>
                    </li>
                    <li>
                        <a href="#">消费者告知书</a>
                        <span>|</span>
                    </li>
                    <li class="person-home-3">
                        <a href="#">更多</a>
                    </li>
                </ul>
            </div>
            <div class="person-home-inner-1">
                <a href="#">我的优惠卷</a>
                <a href="#" style="border-bottom:1px solid #EDEDEE;">我的考拉豆</a>
                <a href="#">账户安全</a>
                <a href="#" style="border-bottom:1px solid #EDEDEE ;">我的实名认证</a>
                <a href="#">我收藏的商品</a>
                <a href="#" style="border-bottom:1px solid #EDEDEE ;">我关注的品牌</a>
                <a href="#">售后管理</a>
            </div>
            <div class="person-home-inner-2">
                <span class="small-pic-1"></span>
                <a href="#" style='padding-left:15px'>联系客服</a>
                <span class="small-pic-2"></span>
                <a href="#" style='padding-left:15px'>帮助中心</a>
            </div>
            <div class="person-home-inner-3">
                <a href="#">收藏本站</a>
                <a href="#" style="border-bottom:1px solid #EDEDEE;">新浪微博</a>
                <a href="#">账户安全</a>
                <a href="#" style="border-bottom:1px solid #EDEDEE ;">微信公众号</a>
                <a href="#">易信公众号</a>
                <a href="#" style="border-bottom:1px solid #EDEDEE ;">招商合作</a>
                <a href="#">考拉招聘</a>
            </div>
        </div>
    </div>
    <div class="header-2">
        <div class="header-2-inner">
            <a href="index.html" class="logo">
                <img src="{% static 'img/logo.jpg' %}"/>
            </a>
            <span class="bg"></span>
        </div>
    </div>
</div>
<div class="mian">
    <div class="cart_box">
        <div class="m_cart_box">
            <div class="head">
                <div class="col1">
                    <input type="checkbox" name="selectall" class="u_chk" isall="{{ isall }}"/>
                    <label for="selectall">全选</label>
                </div>
                <div class="col2">商品信息</div>
                <div class="col3">单价（元）</div>
                <div class="col4">数量</div>
                <div class="col5">金额（元）</div>
                <div class="col6">操作</div>
            </div>
            <div class="m_cart">
                <div class="ware">
                    <ul>
                        {% for cart in carts %}
                            <li>
                                <input type="checkbox" name="cartall" cartid="{{ cart.id }}" isselect="{{ cart.isselect }}"/>
                                <span class="warename"><img src="/static/{{ cart.goods.img }}" style="width: 15%;height: 15%"></span>
                                <span class="price">{{ cart.goods.price }}</span>
                                <span class="number">{{ cart.number }}</span>
                                <span class="total_1">1000</span>
                                <span class="glyphicon glyphicon-remove" id="cross" cartid="{{ cart.id }}"></span>
                            </li>
                        {% endfor %}
                    </ul>

                </div>
                <div class="goods">
                    <ul class="m_goods"></ul>
                    <div class="cartinfo">
                        <span class="discunt"></span>
                        <div class="allsum">
									<span>
										商品应付总计：
										<strong class="totalnum" style="font-size: xx-large"></strong>
									</span>
                        </div>
                        <div class="taxnum">
                            <em class="tt"></em>
                        </div>
                    </div>
                </div>
            </div>
            <div class="totalbox">
                <div class="gobuy">
                    <a href="{% url 'app:generateorder' %}">去结算</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer">

</div>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>登录—网易考拉海外购</title>
		<meta name="keywords" content="网易考拉海购,海淘,跨境购,代购,进口,跨境电商,海外直邮"/>
		<meta name="description" content="网易考拉海购-网易旗下_正品低价_海外直采_海外直邮.网易考拉是国内领先的跨境购物商城，轻松购遍海外进口母婴，进口美食 ，进口美妆、进口电子数码，更多产品正陆续推出。网易考拉海购-安全、放心的跨境购物网站，官方认证，正品保证。"/>
		<link rel="stylesheet" href="{% static 'css/login.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/login.js' %}" ></script>
		<script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
	</head>
	<body>
		<div class="header">
			<div class="header_inner">
				<div class="kaolalogo">
					<a href=""><img src="{% static 'img/logo.jpg' %}"/></a>
				</div>
				<div class="topimg"></div>
			</div>
		</div>
		<div class="main">
			<div class="main-inner">
				<img src="{% static 'picture/login-mian.png' %}" class="lg-img"/>
				<div class="login-table">
					<div class="table-left">
						<div class="table-left-inner">
							<h2 class="title">登陆网易邮箱账号</h2>
                            <form action="{% url 'app:login' %}" method="post">
                                {% csrf_token %}
                                <div class="input-text">
                                    <div class="input-text-1"></div>
                                    <input type="text" placeholder="请输入网易邮箱账号" value="" class="input-text-2" name="account"/>
                                    <div class="input-text-3" style="display: none;"></div>
                                </div>
                                <div class="input-password">
                                    <div class="input-password-1"></div>
                                    <input type="password" placeholder="请输入你的密码" class="input-password-2" name="password"/>
                                    <div class="input-password-3" style="display: none;"></div>
                                </div>
                                <div class="tishi">
                                    阿斯顿发生
                                </div>
                                <div class="input-check">
                                    <div class="input-check-1">
                                        <input type="checkbox" checked="checked" class="input-check-1-1"/>
                                        <span style="color: #999999;">十天内免登陆</span>
                                    </div>
                                    <div class="input-check-2">
                                        <a href="" style="color: #999999;">忘记密码</a>
                                    </div>
                                </div>

                                <input class="denglu" type="submit" value="登&nbsp;&nbsp;陆">


                            </form>
							<div class="zhuce">
                                <span style="color: red">{{ error }}</span>
								<span style="color: #999999;">没有邮箱账号？<a href="">立即注册</a></span>
							</div>
						</div>
					</div>
					<div class="table-footer">
					</div>
					<div class="table-right">
					</div>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="footer-2">
				<div class="bottomTxt">
					<p>
						<a href="#">About NetEase</a> - <a href="#">公司简介</a> - <a href="#">联系方法</a> - <a href="#">友情链接</a> - <a href="#">招聘信息</a> - <a href="#">客户服务 </a> - <a href="#">隐私政策</a> - <a href="#">网络营销</a> - <a href="#">网络地图</a> - <a href="#">网易考拉海购</a>
					</p>
					<p>
						<a class="spanW" href="#">
							<img src="{% static 'picture/f28aa8ee818a42bf832341f605eccefb.png' %}"/>
						</a>
						浙公网安备 33010002000066号&nbsp;&nbsp;增值电信业务经营许可证：浙B2-20090185-3&nbsp;&nbsp;网络文化经营许可证：浙网文[2016]0155-055号&nbsp;&nbsp;网络文化经营许可证：浙网文[2016]0155-055号
					</p>
					<p>
						<span class="spanWrap">
							<img src="{% static 'picture/d720d83b55a04b6f932ea845c673c5bf.png' %}"/>
						</span>
						<span class="spanWrap">
							<img src="{% static 'picture/guohui.jpg' %}">
						</span>
					</p>
				</div>
			</div>
		</div>
	</body>
</html>

templates/orderdetial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情</title>
</head>
<body>
    <h1>订单号：{{ orders.identifier }}</h1>
    <div>
        {% for orderGood in orders.ordergoods_set.all %}
            <span>订单商品信息：{{ orderGood.goods.name }}</span>
            <span>订单商品数量：{{ orderGood.number }}</span>
            <br>
        {% endfor %}
        <button>支付</button>



    </div>



</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>网易用户中心</title>
    <meta name="keywords" content="网易考拉海购,海淘,跨境购,代购,进口,跨境电商,海外直邮"/>
    <meta name="description"
          content="网易考拉海购-网易旗下_正品低价_海外直采_海外直邮.网易考拉是国内领先的跨境购物商城，轻松购遍海外进口母婴，进口美食 ，进口美妆、进口电子数码，更多产品正陆续推出。网易考拉海购-安全、放心的跨境购物网站，官方认证，正品保证。"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
    <script src="{% static 'js/jquery-1.12.3.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.1/css/bootstrap.css" rel="stylesheet">
    <script src="{% static 'js/register.js' %}" type="text/javascript" charset="utf-8"></script>


    <style type="text/css">
        .b-i {
            height: 72px;
            width: 24px;
        }

        .b-i i {
            height: 22px;
            width: 22px;
            float: left;
            padding: 0 2px 0 0;
            background: url({% static 'img/sprite.png' %}) no-repeat -65px -102px;
            margin-bottom: 20px;
        }

        .b-p {
            line-height: 20px;
            overflow: hidden;
            word-break: break-all;
            float: left;
            margin-top: 10px;
        }

        .popb1, .popb2 {
            color: red;
            float: left;
            margin-left: 10px;
            width: 280px;
            height: 45px;
            max-height: 60px;
            overflow: hidden;
            font-size: 12px;
            float: left;
            display: none;
        }

        .popb-i {
            height: 22px;
            width: 22px;
            float: left;
            padding: 0 2px 0 0;
            background: url({% static 'img/sprite.png' %}) no-repeat -30px -102px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
<div class="header">
    <div class="header_logo"></div>
    <div class="header_span">
        <span>已有账号？去<a href="login.html" style="color: darkred;">登录</a></span>
    </div>
</div>
<div class="mian">
    <h2 class="mian_h2">注册账号</h2>
    <form action="{% url 'app:register' %}" method="post">
        {% csrf_token %}
        <div class="formWrap">

            <label for="account" class="labelbox">账号：</label>
            <input id="account" class="form-control" type="text" placeholder="6-18位字母数字组合" name="account"/>
            <select id="mail" name="mail">
                <option>@163.com</option>
                <option>@126.com</option>
                <option>@yeah.net</option>
            </select>
            <table class="popb1">
                <tbody>
                <tr>
                    <td class="b-i"><i></i></td>
                    <td class="b-p">请用字母、数字或下划线命名</td>
                </tr>
                <span style="color: red"></span>
                </tbody>
            </table>
            <span class="popb2"><i class="glyphicon glyphicon-ok"></i></span>
            <br/>

        </div>

        <div class="formWrap">
            <label for="password" class="labelbox">密码：</label>
            <input id="password" type="password" placeholder="6-18位密码，区分大小写" name="password"/>
            <table class="popb1">
                <tbody>
                <tr>
                    <td class="b-i"><i></i></td>
                    <td class="b-p">密码为6-18位数字字母组合</td>
                </tr>
                </tbody>
            </table>
            <span class="popb2"><i class="glyphicon glyphicon-ok" style="color: #4cae4c;size: 20px"></i></span>
            <br/>
        </div>

        <div class="formWrap">
            <label for="comfirm" class="labelbox">确认密码：</label>
            <input id="comfirm" type="password" placeholder="再次输入密码"/>
            <table class="popb1">
                <tbody>
                <tr>
                    <td class="b-i"><i></i></td>
                    <td class="b-p">两次输入密码不一致，请确认重新输入密码</td>
                </tr>
                </tbody>
            </table>
            <span class="popb2"><i class="glyphicon glyphicon-ok" style="color: #4cae4c;size: 20px"></i></span>
            <br/>
        </div>

        <div class="formWrap" style="position:relative;">
            <label for="phone" class="labelbox">手机号：</label>
            <input id="phone" type="text" placeholder="11位手机号" style="display:block" name="phone"/>
            <table class="popb1">
                <tbody>
                <tr>
                    <td class="b-i"><i></i></td>
                    <td class="b-p">请输入有效的手机号</td>
                </tr>
                </tbody>
            </table>
            <span class="popb2"><i class="glyphicon glyphicon-ok" style="color: #4cae4c;size: 20px"></i></i></span>
            <br/>
            <div class="i_phone" style="display:none;">
                <select id="national">
                    <option>美国</option>
                    <option>英国</option>
                    <option>德国</option>
                    <option>意大利</option>
                    <option>比利时</option>
                    <option>奥地利</option>
                    <option>澳大利亚</option>
                    <option>日本</option>
                    <option>韩国</option>
                    <option>俄罗斯</option>
                    <option>朝鲜</option>
                </select>
                <input id="i_phone_number" type="text" placeholder="手机号"/>
                <br/>
            </div>
        </div>

        <div class="formWrap" style="position:relative;">
            <label for="test" class="labelbox">验证码：</label>
            <input id="test" type="text" placeholder="请输入验证码"/><br/>
            <div id="havetext">获取验证码</div>
            <table class="popb1">
                <tbody>
                <tr>
                    <td class="b-i"><i></i></td>
                    <td class="b-p">请输入正确的验证码</td>
                </tr>
                </tbody>
            </table>
            <span class="popb2"><i class="glyphicon glyphicon-ok" style="color: #4cae4c;size: 20px"></i></span>
            <br/>
        </div>

        <div class="formWrap">
            <div class="labelbox2">&nbsp;</div>
            <input type="submit" value="注册" class="zhuce">
        </div>

        <div class="formWrap">
            <div class="labelbox2">&nbsp;</div>
            <div id="tipbox"> 用户注册即代表同意《服务条款》和《网络游戏用户隐私保护和个人信息利用政策》</div>
        </div>

    </form>

</div>
<div class="footer">
    <p class="footTxt1"><a href="#">About NetEase</a> - <a href="#">公司简介</a> - <a href="#">联系方式</a> - <a href="#">OAuth2.0认证</a>
        - <a href="#">招聘信息</a> - <a href="#">客户服务</a> - <a href="#">相关法律</a> - <a href="#">网络营销</a></p>
    <p class="footTxt2">网易公司版权所有 ©1997-2016</p>
</div>
</body>
</html>